title = "Chris's Data Blog"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
disqusShortname = "www-shockleysblog-com"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Some Fun Coding Tutorials/Projects"
  facebook = "fb.me/astronomerforfun"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/saltwater.jpg"
  recent_posts_number = 30
